FROM i386/ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive

USER root

RUN apt-get update \
    && apt-get install -y software-properties-common \
    && apt-get -f install -y \
        build-essential autoconf autogen bison dejagnu flex flip \
        gawk git gperf gzip nsis openssh-client p7zip-full perl \
        python-dev libisl-dev scons tcl texinfo tofrodos wget zip \
        texlive texlive-extra-utils libncurses5-dev

RUN apt-get -f install -y \
    sudo

RUN export uid=1000 gid=1000 && \
    mkdir -p /home/user && \
    echo "user:x:${uid}:${gid}:user,,,:/home/user:/bin/bash" >> /etc/passwd && \
    echo "user:x:${uid}:" >> /etc/group && \
    echo "user ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers && \
    chmod 0440 /etc/sudoers && \
    chown ${uid}:${gid} -R /home/user && \
    usermod -aG dialout user

USER user

ENV HOME /home/user

WORKDIR ${HOME}

CMD bash --login