name: vagrant-build-i386

on: [push]

jobs:
  build:
    runs-on: macos-10.15
    timeout-minutes: 720

    steps:
    - uses: actions/checkout@v2

    - name: Cache Vagrant boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-

    - name: Run vagrant up
      run: vagrant up

    - name: Run scripts
      run: vagrant ssh -c 'cd gcc-arm-none-eabi && sudo sh build.sh'

    - name: Copy ISO from vagrant
      run: vagrant ssh -c 'cat /home/vagrant/gcc-arm-none-eabi/gcc-arm-none-eabi-10.3-2021.10/pkg/gcc-arm-none-eabi-10.3-2022.04-x86_64-linux.tar.bz2' > ~/gcc-arm-none-eabi-10.3-2022.04-x86_64-linux.tar.bz2

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: LFS iso image from Vagrant build
        path: ~/gcc-arm-none-eabi-10.3-2022.04-x86_64-linux.tar.bz2
        retention-days: 5